services:

  frontend:
    build:
      context: ./DockerCourseFrontend/DockerCourseFrontend/.
    image: frontend
    container_name: frontend
    ports:
      - 1234:80

  api:
    build:
      context: ./DockerCourseApi/.
      dockerfile: DockerCourseApi/Dockerfile
    image: api
    container_name: api
    ports:
      - 17860:80
